//created on: Apr 11, 2016
package com.massisframework.massis.dasi.apps.robots.leader

//std imports
import java.util.*;
import java.util.logging.Logger;
import java.util.concurrent.*;
import com.massisframework.massis.dasi.lowlevel.LowLevelInfo;
import com.massisframework.massis.dasi.agents.tasks.AgentTask;
import com.massisframework.massis.dasi.agents.tasks.SimpleTasksFactory;
import com.massisframework.massis.dasi.events.messages.MessageReceived;
import com.massisframework.massis.dasi.agents.goals.*;
//robots
import com.massisframework.massis.dasi.apps.robots.*;
import com.massisframework.massis.dasi.apps.robots.messages.*;
import com.massisframework.massis.dasi.apps.robots.messages.getHelp.*;
import com.massisframework.massis.dasi.apps.robots.messages.knowTeam.*;
import com.massisframework.massis.dasi.apps.robots.messages.orders.*;
import com.massisframework.massis.dasi.apps.robots.messages.saveVictimNegotiation.*;
//leader
import com.massisframework.massis.dasi.apps.robots.leader.info.TermNegotiation.NegotiationStatus;
import com.massisframework.massis.dasi.apps.robots.leader.*;
import com.massisframework.massis.dasi.apps.robots.leader.info.*;
import com.massisframework.massis.dasi.apps.robots.leader.goals.*;
//subordinate
import com.massisframework.massis.dasi.apps.robots.subordinate.SubordinateRobot;
//victim
import com.massisframework.massis.dasi.apps.robots.victim.VictimRobot;
//declare any global variables here

//=============================================================================
// Goal selection
//-----------------------------------------------------------------------------
rule "Generate Goal Memory"
	when
		not GoalMemory(  )
 	then
  		insert(new GoalMemory());
end

rule "Add know my team goal if not present"	
	when
		$gm : GoalMemory( $goals : goals , containsGoalByClass(KnowMyTeam.class)==false)
 	then
 		KnowMyTeam kmt = new KnowMyTeam();
 		insert(kmt);
  	    $gm.addGoal(kmt);
end


//=============================================================================
// Team negotiation rules
//-----------------------------------------------------------------------------
// Goal Trigger
rule "If I dont know my team : The current goal changes."
	when
		$me  : LeaderRobot($team : teamName)
		$gm  : GoalMemory()
		$kmt : KnowMyTeam ( goalState  == AgentGoal.PENDING ) from $gm.goals
 	then
  	   $me.info("If I dont know my team : The current goal changes.", "titulo");
 	   $me.info("No conozco mi equipo.", "info");
 	   String uuid=UUID.randomUUID().toString();
 	   $me.info("Envio mensaje a todos los robots registrados en la simulacion.", "envio");
 	   SimpleTasksFactory.sendMessage($me,new HiTeam($team,uuid));
  	   modify($kmt){ setGoalState( AgentGoal.SOLVED ) }	   
end


rule "Received HiTeamResponseMember"
	when
		$me		: LeaderRobot()
		$mr		: MessageReceived(
							data instanceof HiTeamResponseMember,
							sender instanceof RobotAgent,
							$sender  : sender,
							$info : data.info,
 							$uuid : data.uuid
     						) from entry-point MESSAGING
 	then
 	  $me.info("Received HiTeamResponseMember.", "titulo");
 	  $me.info("He añadido a "+$sender+" a mi pool de miembros de mi equipo.", "info");
 	  $me.info("Le voy a comunicar que ha sido añadido.", "mensaje");
 	  SimpleTasksFactory.sendMessage($me,$sender,new YouArePartOfMyTeam("1",$uuid));
 	  modify($me){ addTeamMember((RobotAgent)$sender)}
 	  retract($mr);
end

rule "Received HiTeamResponseLeader"
	when
		$me		: LeaderRobot()
		$mr		: MessageReceived(
							data instanceof HiTeamResponseLeader,
							sender instanceof RobotAgent,
							$sender  : sender,
							$info : data.info,
 							$uuid : data.uuid
     						) from entry-point MESSAGING
 	then
 	 	$me.info("Received HiTeamResponseLeader.", "titulo");
 	
 	  	$me.info("He añadido a "+$sender+" a mi pool de lideres de equipo.", "info");
 	  	$me.info("Le voy a comunicar que ha sido añadido.", "mensaje");
 	  	SimpleTasksFactory.sendMessage($me,$sender,new AddedToMyPoolLeader("1",$uuid));
 	  	modify($me){ addTeamLeader((RobotAgent)$sender)}
 	  	retract($mr);
end

rule "Received HiTeam"
	when
		$me		: LeaderRobot($team : teamName)
		$mr		: MessageReceived(
							data instanceof HiTeam,
							sender instanceof RobotAgent,
							$sender  : sender,
							$info : data.info,
 							$uuid : data.uuid
     						) from entry-point MESSAGING
     	not(eval($team==$info))
 	then
  	 	$me.info("Received HiTeam.", "titulo");
 		$me.info("He recibido un mensaje de Hola de "+$sender+".", "info");
 		$me.info("Le voy a comunicar que soy un lider.", "mensaje");
 	  	SimpleTasksFactory.sendMessage($me,$sender,new HiTeamResponseLeader($team,$uuid));
 	  	retract($mr);
end


rule "AddedToPoolLeader"
	when
		$me		: LeaderRobot($team : teamName)
		$mr		: MessageReceived(
							data instanceof AddedToMyPoolLeader,
							sender instanceof RobotAgent,
							$sender  : sender,
							$info : data.info,
 							$uuid : data.uuid
     						) from entry-point MESSAGING
 	then  	 	
 		$me.info("AddedToPoolLeader.", "titulo");
    	$me.info($sender+" me ha añadido a su pool de lideres de equipo.", "info");
 	  	retract($mr);
end




//==================================================================================
// Victim saving
//----------------------------------------------------------------------------------
rule "Receive I have no energy message"
    when
       $me	: LeaderRobot($teamLeaders : teamLeaders)
       $gm  : GoalMemory( $goals : goals)
       $mr  : MessageReceived(
							data instanceof IHaveNoEnergy,
							sender instanceof VictimRobot,
							$sender  : sender,
							$location : data.info,
							$uuid : data.uuid
     						) from entry-point MESSAGING
 	then
	   	$me.info("Receive I have no energy message.", "titulo");
    	$me.info("Recibida solicitud de ayuda de "+$sender+" en el punto "+$location, "info");
 	  	$me.info("Envio de ACK a "+$sender+".", "envio");
	   	SimpleTasksFactory.sendMessage($me,$sender,new IKnowYourState($uuid));
	 
	 	insert(new TeamNegotiationToSaveVictim($teamLeaders.size(),(VictimRobot)$sender,NegotiationStatus.NOT_STARTED));
	
	   	HelpVictim hv = new HelpVictim((VictimRobot)$sender);
	   	insert(hv);
	   	$gm.addGoal(hv);
	   	retract($mr);
end







rule "Negotiation save victim not started"
    when
       //Soy un lider.
       $me	: LeaderRobot($teamLeaders: teamLeaders )

		$tnl : TeamNegotiationToSaveVictim(
					$victim : victim,
					nResponse>0,
					status==NegotiationStatus.NOT_STARTED)
       $gm : GoalMemory( )
       //Exite un objetivo que es ayudar a la victima y esta pendiente.
       $kmt : HelpVictim ( $victim == goalData, 
       					goalState  == AgentGoal.PENDING ) from $gm.goals
     then
		String uuid=UUID.randomUUID().toString();
	   	$me.info("Negotiation save victim not started.", "titulo");
    	$me.info("Envio broadcast a todos los lideres para que tramiten la evaluacion de la victima "+$victim+".", "envio");
	   	SimpleTasksFactory.sendMessageMultiples($me,$teamLeaders, 
	   		new SaveVictimNegotiationTerms(
	   		new NegotiationTerms($me.getFloatBestIdleAgent($victim),$victim),uuid));	
   	    $me.info("Paso a esperar respuesta.", "info");
	   	modify($tnl){setStatus(NegotiationStatus.WAITING_FOR_RESPONSE)}
end


rule "I receive one message about victim negotiation. $tr<bestEva"
	when
       	$me	: LeaderRobot()
       	$mr		: MessageReceived(
					data instanceof SaveVictimNegotiationTerms,
					sender instanceof RobotAgent,
					$sender  : sender,
					$tr : data.info,
					$uuid : data.uuid
 				) from entry-point MESSAGING	
		$tnl : TeamNegotiationToSaveVictim(
       				$b : bestEva,
					$victim : victim,
					$victim == $tr.getVictim(),
					status==NegotiationStatus.WAITING_FOR_RESPONSE)
		eval( ($b > $tr.getValue() && $tr.getValue()>-1) || $b == -1)
	then
		$me.info("I receive one message about victim negotiation. $tr<bestEva", "titulo");
    	$me.info("He recibido una valoracion que es mejor que cualquiera que haya recibido antes para la victima "+$victim+".", "info");
   		$tnl.setBestEva($tr.getValue());
		modify($tnl){setNResponse(1)}
	   	retract($mr);		
end





rule "I receive one message about victim negotiation. bestEva<Nueva valoracion."
	when
	   	//Soy un lider.
       	$me	: LeaderRobot()
       	//He recibido una valoracion para una tarea de rescate.
       	$mr		: MessageReceived(
					data instanceof SaveVictimNegotiationTerms,
					sender instanceof RobotAgent,
					$sender  : sender,
					$tr : data.info,
					$uuid : data.uuid
 				) from entry-point MESSAGING	
		$tnl : TeamNegotiationToSaveVictim(
       				$b :	bestEva,
					$victim : victim,
					$victim == $tr.getVictim(),
					
					status==NegotiationStatus.WAITING_FOR_RESPONSE)
		eval(($b>-1 && $b<$tr.getValue())|| $tr.getValue()==-1)
	then
		$me.info("I receive one message about victim negotiation. bestEva<Nueva valoracion.", "titulo");
    	$me.info("He recibido una nueva valoracion para la victima "+$victim+" pero es peor que la mejor que he recibido.", "info");
		modify($tnl){setNResponse(1)}
	   	retract($mr);		
end






rule "Save victim?? Yes"
	when
       $gm : GoalMemory( )
       $me	: LeaderRobot($teamLeaders: teamLeaders )
       $tnl : TeamNegotiationToSaveVictim(
					$victim : victim,
					$be : bestEva,
					nResponse<=0
					)
       
		eval($me.getFloatBestIdleAgent($victim)>-1)
       	eval($be==-1 || $be>$me.getFloatBestIdleAgent($victim))
       
		$kmt : HelpVictim ( $victim == goalData, 
       					goalState  == AgentGoal.PENDING ) from $gm.goals
       					
   	  	not (exists ( VictimAssignedToSubordinate($me.getBestIdleAgent($victim) == subordinate)))		
     then
    	$me.info("Save victim?? Yes", "titulo");
    	$me.info("Mi equipo tiene la mejor valoracion para "+$victim+".", "info");
		
    	RobotAgent s =	$me.getBestIdleAgent($victim);
	   	String uuid=UUID.randomUUID().toString();
		SimpleTasksFactory.sendMessage($me,s,new SaveVictim($victim,uuid));

		$me.info("El robot "+s+" tiene la tarea de rescatar a "+$victim+".", "envio");
		
		insert(new VictimAssignedToSubordinate($victim, s));
		retract($tnl);
   	   	modify($kmt){ setGoalState( AgentGoal.SOLVING ) }	  
end




rule "Save victim?? No"
	when
       $gm : GoalMemory( )
       $me	: LeaderRobot($teamLeaders: teamLeaders )
       $tnl : TeamNegotiationToSaveVictim(
					$victim : victim,
					$be : bestEva,
					bestEva>-1,
					nResponse<=0,
					status==NegotiationStatus.WAITING_FOR_RESPONSE)       
       	eval($be<$me.getFloatBestIdleAgent($victim))
		$kmt : HelpVictim ( $victim == goalData, 
       					goalState  == AgentGoal.PENDING ) from $gm.goals
     then
     	$me.info("Save victim?? No", "titulo");
    	$me.info("Mi equipo no tiene la mejor valoracion para "+$victim+" pero alguien puede asistirla.", "info");
		
		retract($tnl);  	   	
  	   	modify($kmt){ setGoalState( AgentGoal.SOLVED ) }	  
end


rule "Save victim?? Pending"
	when
       $gm : GoalMemory( )
       $me	: LeaderRobot($teamLeaders: teamLeaders )
       $tnl : TeamNegotiationToSaveVictim(
					$victim : victim,
					$be : bestEva,
					nResponse<=0
					)       
       	eval($me.getFloatBestIdleAgent($victim)==-1)
       	eval($be==-1)
		$kmt : HelpVictim ( $victim == goalData, 
       					goalState  == AgentGoal.PENDING ) from $gm.goals
     then
     	$me.info("Save victim?? Pending", "titulo");
    	$me.info("Nadie puede rescatar por ahora a "+$victim+" este objetivo se mantiene pendiente.", "info");
		retract($tnl);  	   	
end



rule "Receive notification about victim saved - PENDING GOAL"
    when
        $gm : GoalMemory( )
    
       	$me	: LeaderRobot($teamLeaders : teamLeaders)
       	$mr	: MessageReceived(
							data instanceof VictimSaved,
							$sender : sender instanceof RobotAgent,
							$victim : data.info
     						) from entry-point MESSAGING					
     	$vas : VictimAssignedToSubordinate(victim == $victim)
     	
     	$kmt : HelpVictim ( $victim == goalData, 
       					goalState  == AgentGoal.SOLVING ) from $gm.goals
     	
     	$kmt2 : HelpVictim ( $victim2 : goalData, 
       					goalState  == AgentGoal.PENDING ) from $gm.goals
		not(exists( TeamNegotiationToSaveVictim($victim2 == victim)))
     	
    then
    	$me.info("Receive notification about victim saved - PENDING GOAL", "titulo");
    	$me.info("He recibido una notificacion de rescate realizado, y tengo tareas pendientes de reevaluar.\n"+
    	"NO PROCESO LA ELIMINACION DEL MENSAJE TODAVIA.", "info");
	 	insert(new TeamNegotiationToSaveVictim($teamLeaders.size(),(VictimRobot)$victim2,NegotiationStatus.NOT_STARTED));
end



rule "Receive notification about victim saved - NO PENDING GOAL"
    when
        $gm : GoalMemory( )
    
       $me	: LeaderRobot()
       $mr	: MessageReceived(
							data instanceof VictimSaved,
							$sender : sender instanceof RobotAgent,
							$victim : data.info
     						) from entry-point MESSAGING
      	$vas : VictimAssignedToSubordinate(victim == $victim)
     	$kmt : HelpVictim ( $victim == goalData, 
       					goalState  == AgentGoal.SOLVING ) from $gm.goals
    then
    	$me.info("Receive notification about victim saved - NO PENDING GOAL", "titulo");
    	$me.info("Proceso la eliminacion del mensaje de tarea realizada y paso el objetivo a solucionado.", "info");
		modify($kmt){ setGoalState( AgentGoal.SOLVED ) }	
	   	retract($mr);
	   	retract($vas);
end