//created on: Apr 13, 2016
package com.massisframework.massis.dasi.agents.common.goals

//list any import classes here.
import com.massisframework.massis.dasi.agents.common.*;
import com.massisframework.massis.dasi.agents.common.info.*;
import com.massisframework.massis.dasi.agents.common.goals.*;
import com.massisframework.massis.dasi.agents.common.goals.movement.*;
import com.massisframework.massis.dasi.agents.common.tasks.*;
import com.massisframework.massis.dasi.agents.common.tasks.movement.*;
import com.massisframework.massis.dasi.agents.common.goals.AgentGoal.GoalEvaluation;
import com.massisframework.massis.dasi.agents.common.goals.AgentGoal.GoalState;
//declare any global variables here


rule "Insert goal memory"

    when
        not (exists GoalMemory())
    then
       System.out.println("Inserting goal memory");
       insert(new GoalMemory());
end



rule "If the current goal was not solved, and passes the evaluation, mark it as solved"
	when
		$gm : GoalMemory($cg : currentGoal , currentGoal!=null, $cg.goalState != GoalState.SOLVED)
		eval($cg.evaluateNow() == GoalEvaluation.PASSED)
	then
		System.out.println("Marking as solved");
	   modify($cg){setGoalState(GoalState.SOLVED)}
end

// Common goals & tasks

rule "If the current goal is to move, move"
	when
		$lli : LowLevelInfo($lla : lowLevelAgent, $tick:tick)
		$gm : GoalMemory(
						$cg : currentGoal,
						currentGoal!=null,
						currentGoal instanceof ReachLocation,
						$cg.goalState == GoalState.PENDING,
						$target : currentGoal.goalData.target					
						)
	then
	 	new MoveTo().execute($lla, $target);
end




