//created on: Apr 13, 2016
package com.massisframework.massis.dasi.lowlevel

//list any import classes here.

import java.awt.geom.Point2D;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;


import com.massisframework.massis.model.agents.LowLevelAgent;
import com.massisframework.massis.model.building.SimRoom;
import com.massisframework.massis.model.location.Location;



rule "update Location"
	ruleflow-group "lowlevelupdate"
    when
    	SimTick( $tick : tick )
        $lli : LowLevelInfo(
        					tick!=$tick,
        					$lla: lowLevelAgent,
        					shouldUpdateLocation == true)
    then
      // System.out.println("update loc");
       modify($lli) { setTick($tick) }
       modify($lli) { setLocation($lla.getLocation()) }
       update($lli);
       
       
end


rule "update vision radio"
  ruleflow-group "lowlevelupdate"
  when
    
    	SimTick( $tick : tick )
        $lli : LowLevelInfo($lla: lowLevelAgent,tick!=$tick,shouldUpdateAgentsVisionRadio == true)
    then
    	modify($lli) { setTick($tick) }
    	modify($lli){ setAgentsInVisionRadio($lla.getAgentsInVisionRadio()) }
end



rule "update acceleration"
	ruleflow-group "lowlevelupdate"
	when
		SimTick( $tick : tick )
		$lli : LowLevelInfo($lla: lowLevelAgent,tick!=$tick,shouldUpdateAcceleration == true)
	then
		modify($lli) { setTick($tick) }
		modify($lli) {
					setAcceleration(
						$lla.getAcceleration().getX(),
						$lla.getAcceleration().getY()
						)
					 }
end


rule "update agents in room"
  ruleflow-group "lowlevelupdate"
  when
    
    	SimTick( $tick : tick )
        $lli : LowLevelInfo($lla: lowLevelAgent,tick!=$tick,shouldUpdateAgentsInRoom == true)
    then
    	modify($lli) { setTick($tick) }
    	modify($lli){ setAgentsInRoom($lla.getAgentsInRoom()) }
end

rule "update body radio"
 	ruleflow-group "lowlevelupdate"
  when
    
    	SimTick( $tick : tick )
        $lli : LowLevelInfo($lla: lowLevelAgent,tick!=$tick,shouldUpdateBodyRadius == true)
    then
    	modify($lli) { setTick($tick) }
    	modify($lli){ setBodyRadius($lla.getBodyRadius()) }
end


rule "update current room"
 	ruleflow-group "lowlevelupdate"
  when
    
    	SimTick( $tick : tick )
        $lli : LowLevelInfo($lla: lowLevelAgent,tick!=$tick,shouldUpdateCurrentRoom == true)
    then
    	modify($lli) { setTick($tick) }
    	modify($lli){ setCurrentRoom($lla.getRoom()) }
end

rule "update rooms in floor information"
	ruleflow-group "lowlevelupdate"
    when
    	SimTick( $tick : tick )
        $lli : LowLevelInfo($lla: lowLevelAgent,tick!=$tick,shouldUpdateRoomsInFloor == true)
    then
    	modify($lli) { setTick($tick) }
    	modify($lli){ setRoomsInFloor($lla.getLocation().getFloor().getRooms()) }
end

